---
- name: Install addtional profiles
  ansible.builtin.apt:
    name: apparmor-profiles
    state: present

- name: Ensure apparmor is enabled
  ansible.builtin.service:
    name: apparmor
    enabled: true

- name: Ensure apparmor is running
  ansible.builtin.service:
    name: apparmor
    state: started
