---
- name: Ensure everything is up to date and patched
  ansible.builtin.apt:
    update_cache: true
    upgrade: true
    force_apt_get: true

- name: Install common packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - aptitude
    - unattended-upgrades

- name: Enforce automatic updates
  ansible.builtin.copy:
    src: apt/20auto-upgrades
    dest: "{{ apt_conf_d }}"
    mode: "0644"
