---
- name: Install auditd
  ansible.builtin.apt:
    name: auditd
    state: present

- name: Start the auditd service
  ansible.builtin.service:
    name: auditd
    state: started
    enabled: true

# NOTE: Is the audit dir (/var/log/audit/audit.log) audited?
- name: Create /tmp rules
  ansible.builtin.copy:
    src: audit/tmp.rules
    dest: "{{ audit_rules_dir }}"
    mode: "0644"

  notify: Rule merge

- name: Create admin home rules
  ansible.builtin.copy:
    src: audit/admin-home.rules
    dest: "{{ audit_rules_dir }}"
    mode: "0644"
  notify: Rule merge
