---
- name: Install the b2 python package so duplicity can use it
  ansible.builtin.pip:
    name: "b2=={{ backups_b2_version }}"

- name: authorise access to b2
  ansible.builtin.command:
    argv:
      - "b2"
      - "authorize-account"
      - "{{ b2_unifi_backups_application_key_id }}"
      - "{{ b2_unifi_backups_application_key }}"
  creates: /root/.b2_account_info

- name: setup b2 systemd timer
  copy:
    src: "backups/b2-backup.timer"
    dest: "/etc/systemd/system/b2-backups.timer"

- name: setup b2 systemd service
  template:
    src: "backups/b2-backup.service.j2"
    dest: "/etc/systemd/system/b2-backups.service"

- name: enable and start systemd timer
  ansible.builtin.systemd:
    name: b2-backups.timer
    state: started
    enabled: yes
    masked: no
  when: not testing | default('no') | bool
