---
- name : Format data disk if not already
  filesystem:
    fstype: "{{ data_disk_fs_type }}"
    dev: "{{ data_disk_device_path }}"

- name: Create mount point directory for data disk
  file:
    path: "{{ data_disk_mount_point }}"
    state: directory

- name: Update fstab and mount the disk
  mount:
    name: "{{ data_disk_mount_point }}"
    src: "{{ data_disk_device_path }}"
    opts: noatime
    fstype: "{{ data_disk_fs_type }}"
    state: mounted
