---
- name: Install Docker dependencies
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - python3-docker
    - apt-transport-https
    - ca-certificates
    - software-properties-common

- name: Create temporary file to place docker respository GPG key
  ansible.builtin.tempfile:
    state: file
  register: tempory_key

- name: Copy over docker respository GPG key
  ansible.builtin.copy:
    src: docker/docker.gpg
    dest: "{{ tempory_key.path }}"
    mode: "0644"

- name: Add docker respository GPG key
  ansible.builtin.apt_key:
    file: "{{ tempory_key.path }}"
    state: present

- name: Add docker repository
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu "{{ docker_ubuntu_release }}" stable
    state: present
    filename: docker

- name: Ensure config directories exist
  ansible.builtin.file:
    path: "{{ docker_config_directory_path }}"
    state: directory
    mode: "0755"

- name: Create docker data directory
  ansible.builtin.file:
    path: "{{ docker_config['data-root'] }}"
    state: directory
    mode: "0755"

- name: Write out config file
  ansible.builtin.copy:
    content: "{{ docker_config | to_json }}"
    dest: "{{ docker_config_file_path }}"
    mode: "0644"

- name: Install docker
  ansible.builtin.apt:
    name: docker-ce
    state: present
    update_cache: true

- name: Ensure docker is running
  ansible.builtin.service:
    name: docker
    state: started
    masked: false
    enabled: true
