---
- name: Ensure ufw is installed
  ansible.builtin.apt:
    name: ufw
    state: present

# UFW has it's own service management layer. So no service module needed
- name: Start the ufw service
  community.general.ufw:
    state: enabled

- name: Setup default outgoing rule
  community.general.ufw:
    rule: allow
    direction: out

- name: Limit number of SSH connections
  community.general.ufw:
    rule: limit
    port: ssh
    proto: tcp
  when: enable_ssh

- name: Allow SSH access
  community.general.ufw:
    rule: allow
    name: OpenSSH
  when: enable_ssh

- name: Disable SSH access if requested
  community.general.ufw:
    rule: reject
    name: OpenSSH
  when: not enable_ssh

- name: Set default incoming rule
  community.general.ufw:
    rule: deny
    direction: in
