---
- name: Gather facts
  ansible.builtin.setup:
    gather_subset: all
- ansible.builtin.include_tasks: apt.yml
  when: not testing | default('no') | bool
- ansible.builtin.include_tasks: disks.yml
- ansible.builtin.include_tasks: swap.yml
- ansible.builtin.include_tasks: auditd.yml
- ansible.builtin.include_tasks: apparmor.yml
- ansible.builtin.include_role:
    name: dev-sec.os-hardening
  when: not testing | default('no') | bool
- ansible.builtin.include_tasks: timesync.yml
  when: not testing | default('no') | bool
#- include_tasks: cagent.yml
#- include_tasks: logdna.yml
#  when: not testing | default('no') | bool
- ansible.builtin.include_tasks: firewall.yml

- ansible.builtin.include_tasks: secrets.yml
  when: not testing | default('no') | bool

- include_tasks: backups.yml
  when: not testing | default('no') | bool

- ansible.builtin.include_tasks: rebuild.yml

- ansible.builtin.include_tasks: docker.yml
- ansible.builtin.include_tasks: nginx.yml
- ansible.builtin.include_tasks: certbot.yml
- ansible.builtin.include_tasks: unifi.yml
