---
- name: Make nginx config directory
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
  loop:
    - "{{ nginx_config_path }}"
    - "{{ nginx_certs_path }}"
    - "{{ nginx_config_webgateway_path }}"

- name: Create default configuration
  template:
    src: nginx/default.conf.j2
    dest: "{{ nginx_default_config_path }}"

- name: Install Nginx image
  docker_container:
    name: nginx
    image: "nginx:{{ nginx_version }}"
    state: started
    restart: yes
    published_ports:
      - "0.0.0.0:80:80/tcp"
      - "0.0.0.0:443:443/tcp"
    volumes:
      - "{{ nginx_config_path }}:{{ nginx_config_volume_path }}:ro"
      - "{{ nginx_certs_path }}:{{ nginx_certs_volume_path }}:ro"
      - "{{ nginx_web_root_path }}:{{ nginx_web_root_volume_path }}:ro"

- name: Allow http access
  ufw:
    rule: allow
    port: '80'
    proto: tcp

- name: Create Nginx web gateway network for other containers running webservers to serve through
  community.docker.docker_network:
    name: "{{ webgateway_network_name }}"
    connected:
      - nginx
