---
- name: Get secrets url
  command:
    cmd: "scw-userdata doppler-project-url"
  register: secret_url

- name: Get secret to access secret
  command:
    cmd: "scw-userdata doppler-project-secret"
  register: secret_secret


- name: Install jq
  apt:
    name: jq
    state: present

- name: Get secrets from Doppler
  ansible.builtin.shell:
    cmd: |
      curl https://api.doppler.com/v3/configs/config/secrets?project=unifi\&config=prd \
        --header 'authorization: Bearer {{ secret_secret.stdout }}' |
          jq '.secrets | with_entries(.value |= .computed)' > /tmp/secrets.json

- name: load secrets
  ansible.builtin.include_vars:
    file: /tmp/secrets.json
    name: secrets