---
- name: Get secrets url
  ansible.builtin.command:
    cmd: "scw-userdata doppler-project-url"
  register: secret_url
  changed_when: true

- name: Get secret to access secret
  ansible.builtin.command:
    cmd: "scw-userdata doppler-project-secret"
  register: secret_secret
  changed_when: true

- name: Install jq
  ansible.builtin.apt:
    name: jq
    state: present

- name: Get secrets from Doppler
  ansible.builtin.shell:
    cmd: |
      set -o pipefail && curl https://api.doppler.com/v3/configs/config/secrets?project=unifi\&config=prd \
        --header 'authorization: Bearer {{ secret_secret.stdout }}' |
          jq '.secrets | with_entries(.value |= .computed)' > /tmp/secrets.json
    executable: /bin/bash
  args:
    creates: /tmp/secrets.json

- name: Load secrets
  ansible.builtin.include_vars:
    file: /tmp/secrets.json
    name: secrets
