---
- name: Get secrets url
  ansible.builtin.command:
    cmd: "scw-userdata doppler-project-url"
  register: secret_url
  changed_when: true

- name: Get secret to access secret
  ansible.builtin.command:
    cmd: "scw-userdata doppler-project-secret"
  register: secret_secret
  changed_when: true

- name: Install jq
  ansible.builtin.apt:
    name: jq
    state: present

- name: Download secrets from Doppler
  ansible.builtin.get_url:
    url: "{{ secret_url.stdout }}"
    dest: /tmp/secrets-all.json
    mode: "0644"
    headers:
      authorization: "Bearer {{ secret_secret.stdout }}"

- name: Convert Doppler secrets to vars
  ansible.builtin.shell:
    cmd: |
      set -o pipefail && cat /tmp/secrets-all.json |
          jq '.secrets | with_entries(.value |= .computed)' > /tmp/secrets.json
    executable: /bin/bash
  args:
    creates: /tmp/secrets.json

- name: Load secrets
  ansible.builtin.include_vars:
    file: /tmp/secrets.json
    name: secrets
