---
- name: Create swap file
  ansible.builtin.command: "dd if=/dev/zero of={{ swap_file_path }} bs={{ ansible_memtotal_mb }} count=1048576"
  args:
    creates: "{{ swap_file_path }}"

- name: Format swap
  community.general.filesystem:
    fstype: swap
    dev: "{{ swap_file_path }}"

- name: Enable swap
  ansible.builtin.command: "swapon {{ swap_file_path }}"
  changed_when: true
