---
- name: Make unifi config directories
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
  loop:
    - "{{ unifi_base_path }}"
    - "{{ unifi_config_path }}"

- name: Install Jellyfin image
  docker_container:
    name: unifi
    image: "linuxserver/unifi-controller:{{ unifi_version }}"
    container_default_behavior: compatibility
    state: started
    restart: yes
    published_ports:
      - "0.0.0.0:3478:3478/udp"
      - "0.0.0.0:8080:8080/udp"

    volumes:
      - "{{ unifi_config_path }}:{{ unifi_config_volume_path }}"

- name: Connect to web gateway network to communicate with nginx
  community.general.docker_network:
    name: "{{ webgateway_network_name }}"
    connected:
      - nginx
    appends: yes
  notify:
    - Restart Nginx
