---
- name: Make unifi config directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    recurse: true
  loop:
    - "{{ unifi_base_path }}"
    - "{{ unifi_config_path }}"

- name: Create unifi configuration for nginx
  ansible.builtin.template:
    src: nginx/unifi.conf.j2
    dest: "{{ nginx_config_webgateway_path }}/unifi.conf"
    mode: "0644"

- name: Install Unifi image
  community.docker.docker_container:
    name: unifi
    image: "linuxserver/unifi-network-application:{{ unifi_version }}"
    state: started
    restart: true
    published_ports:
      - "0.0.0.0:3478:3478/udp"
      - "0.0.0.0:8080:8080/tcp"

    volumes:
      - "{{ unifi_config_path }}:{{ unifi_config_volume_path }}"

- name: Allow STUN UDP port
  community.general.ufw:
    rule: allow
    port: 3478
    proto: udp

- name: Device and application communication
  community.general.ufw:
    rule: allow
    port: 8080
    proto: tcp

- name: Connect to web gateway network to communicate with nginx
  community.docker.docker_network:
    name: "{{ webgateway_network_name }}"
    connected:
      - unifi
    appends: true
  notify:
    - Restart Nginx
