---
- name: Make unifi config directories
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
  loop:
    - "{{ unifi_base_path }}"
    - "{{ unifi_config_path }}"

- name: Create unifi configuration for nginx
  template:
    src: nginx/unifi.conf.j2
    dest: "{{ nginx_config_webgateway_path }}/unifi.conf"

- name: Install Unifi image
  docker_container:
    name: unifi
    image: "linuxserver/unifi-controller:{{ unifi_version }}"
    state: started
    restart: yes
    published_ports:
      - "0.0.0.0:3478:3478/udp"
      - "0.0.0.0:8080:8080/tcp"

    volumes:
      - "{{ unifi_config_path }}:{{ unifi_config_volume_path }}"

- name: Allow STUN UDP port
  ufw:
    rule: allow
    port: 3478
    proto: udp

- name: device and application communication
  ufw:
    rule: allow
    port: 8080
    proto: tcp

- name: Connect to web gateway network to communicate with nginx
  community.general.docker_network:
    name: "{{ webgateway_network_name }}"
    connected:
      - unifi
    appends: yes
  notify:
    - Restart Nginx
