---
# Handler for auditd service
- name: Rule merge
  ansible.builtin.command: augenrules
  notify: Restart auditd

- name: Restart auditd
  ansible.builtin.service:
    name: auditd
    state: restarted

# Handler for firewalld service
- name: Restart ufw
  ansible.builtin.service:
    name: ufw
    state: restarted

# Handler for nginx service
- name: Restart Nginx
  community.docker.docker_container:
    name: nginx
    state: started
    restart: true
