---
name: Ansible Role Test
on:
  - push

jobs:
  lint:
    name: Lint the Ansible
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install ansible==5.2.0 molecule==3.5.2
      - name: Run molecule
        run: |
          molecule lint
          molecule syntax
  test:
    name: Run Tests
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install python3
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install ansible
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install ansible==5.2.0
      - name: Create file to simulate an attached disk
        run: sudo truncate -s 5G /testdisk
      - name: Install this role locally
        run: ansible-galaxy install git+https://github.com/${GITHUB_REPOSITORY}.git
      - name: Run role
        run: ansible --become --connection=local --inventory 127.0.0.1, --extra-vars "@tests/extra-vars.yml" --module-name include_role -a name=ansible-role-media localhost
      - name: Run tests
        run: ansible --become --connection=local --inventory 127.0.0.1, --module-name include_role -a name=tests localhost
  trigger:
    name: If Lint and Test is successful trigger update on infrastructure
    needs:
      - lint
      - test
    runs-on: ubuntu-20.04
    steps:
      - name: Trigger update to instance
        uses: mvasigh/dispatch-action@main
        with:
          token: ${{ secrets.TF_MEDIA_PERSONAL_ACCESS_TOKEN }}
          repo: tf-media
          owner: yamatt
          event_type: update
